html stuff/uno/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("adriel", views.adriel, name="adriel"),
    path("mary", views.mary, name="mary")
]

html stuff/uno/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

html stuff/uno/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

html stuff/uno/uno/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('tasks/', include("tasks.urls")),
    path('newyear/', include("newyear.urls"))
]

html stuff/uno/hello/models.py
from django.db import models

# Create your models here.

html stuff/uno/newyear/models.py
from django.db import models

# Create your models here.

html stuff/uno/tasks/models.py
from django.db import models

# Create your models here.

html stuff/uno/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def adriel(request):
    return HttpResponse("Hello, Adriel!")

def mary(request):
    return HttpResponse("Hello, Mary!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

html stuff/uno/newyear/views.py
import datetime
from django.shortcuts import render

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1
    })

html stuff/uno/tasks/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django import forms


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    #priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
            
        else:
            return render(request, "tasks/add.html", {
                "form": form
            })

    return render(request, "tasks/add.html", {
        "form": NewTaskForm()
    })

html stuff/uno/hello/templates/hello/greet.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, {{ name }}!</h1>
</body>
</html>

html stuff/uno/hello/templates/hello/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello {{ name }}</h1>
    
</body>
</html>

html stuff/uno/newyear/templates/newyear/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Is it New Year's?</title>
    <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
</body>
</html>

html stuff/uno/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

html stuff/uno/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
<ol>
    {% for task in tasks %}
        <li>{{ task }}</li>
    {% empty %}
        <p>No tasks.</p>
    {% endfor %}
</ol>
<a href="{% url 'tasks:add' %}">Add Tasks </a>
{% endblock %}

html stuff/uno/tasks/templates/tasks/layout.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tasks</title>
</head>
<body>
    <h1>Tasks</h1>
    {% block body %}
    {% endblock %}
</body>
</html>